### ISSUE TITLE
Submitting to conda-forge

### ISSUE THREAD

**Issue by jankatins** [menpo/conda-ffmpeg#1]
It would be great if this package (including a versions for linux) could be submitted to conda-forge so that it is available in that channel. I'm currently looking for ffmpeg to install it for pythons matplotlib...

**Comment by patricksnape** [comment]
I believe that we [have an ffmpeg](https://github.com/conda-forge/ffmpeg-feedstock) recipe for conda-forge?

**Comment by jankatins** [comment]
damn, I only tried on windows, which the repo skips :-(  I opened https://github.com/conda-forge/ffmpeg-feedstock/issues/7
